test pipeline

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,7 +9,6 @@ on:
       - main
 
 jobs:
-
   sonarcloud:
     name: SonarCloud
     runs-on: ubuntu-latest
@@ -79,11 +78,8 @@ jobs:
           name: dependency-scan-report
           path: dependency-check-report.html
 
-
-#####
   build_and_push_docker_images:
     runs-on: ubuntu-latest
-    needs: snyk 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -131,14 +127,48 @@ jobs:
         uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
         with:
           image-ref: 'shate1/my-rails-app:latest'
-
+          severity: 'HIGH,CRITICAL'
+          exit-code: 0
+        continue-on-error: true
 
       - name: Scan Docker image for vulnerabilities shate1/my-nginx-app:latest'
         uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
         with:
           image-ref: 'shate1/my-nginx-app:latest'
+          severity: 'HIGH,CRITICAL'
+          exit-code: 0
+        continue-on-error: true
 
       - name: Scan Docker image for vulnerabilities shate1/my-ruby-app:latest'
         uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
         with:
           image-ref: 'shate1/my-ruby-app:latest'
+          severity: 'HIGH,CRITICAL'
+          exit-code: 0
+        continue-on-error: true
+
+      - name: Fail pipeline if vulnerabilities found
+        run: |
+          VULNERABILITIES_FOUND=false
+          
+          if grep -q "Vulnerabilities found" trivy_scan_rails.log; then
+            echo "Vulnerabilities found in Rails app"
+            VULNERABILITIES_FOUND=true
+          fi
+
+          if grep -q "Vulnerabilities found" trivy_scan_nginx.log; then
+            echo "Vulnerabilities found in Nginx app"
+            VULNERABILITIES_FOUND=true
+          fi
+
+          if grep -q "Vulnerabilities found" trivy_scan_ruby.log; then
+            echo "Vulnerabilities found in Ruby app"
+            VULNERABILITIES_FOUND=true
+          fi
+
+          if [ "$VULNERABILITIES_FOUND" = true ]; then
+            echo "Critical vulnerabilities found. Failing the pipeline."
+            exit 1
+          else
+            echo "No critical vulnerabilities found."
+          fi
