test pipeline

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,8 +9,14 @@ on:
 jobs: 
   build_and_push_docker_images:
     runs-on: ubuntu-latest
-    if: ${{ success() }}
     steps:
+
+      - name: Fail if Test failed
+        if: ${{ github.event.workflow_run.conclusion != 'success' }} 
+        run: |
+          echo "Test_Code failed. Failing CI pipeline."
+          exit 1  
+    
       - name: Checkout code
         uses: actions/checkout@v4
 
