test pipeline

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,17 +5,18 @@ on:
     workflows: ["Test_Code"]
     types:
       - completed 
+    if: ${{ github.event.workflow_run.conclusion != 'success' }} 
 
 jobs: 
   build_and_push_docker_images:
     runs-on: ubuntu-latest
     steps:
 
-      - name: Fail if Test failed
-        if: ${{ github.event.workflow_run.conclusion != 'success' }} 
-        run: |
-          echo "Test_Code failed. Failing CI pipeline."
-          exit 1  
+      # - name: Fail if Test failed
+      #   if: ${{ github.event.workflow_run.conclusion != 'success' }} 
+      #   run: |
+      #     echo "Test_Code failed. Failing CI pipeline."
+      #     exit 1  
     
       - name: Checkout code
         uses: actions/checkout@v4
